function g(k,d){return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}function s(k,v){localStorage.setItem(k,JSON.stringify(v))}
function login(){localStorage.setItem('user',document.getElementById('username').value||'User');location='dashboard.html'}
function loadDashboard(){let r=g('resources',[]),q=g('requests',[]),a=g('history',[]);document.getElementById('stats').innerHTML='Resources:'+r.length+' Pending:'+q.filter(x=>x.status!=='Assigned').length+' Allocations:'+a.length;document.getElementById('ai').innerText='AI Insight: Prioritize high urgency requests and nearest matching resources.'}
function addResource(){let r=g('resources',[]);r.push({name:rname.value,type:rtype.value,loc:rloc.value,status:'Available'});s('resources',r);renderResources()}
function renderResources(){let r=g('resources',[]);let el=document.getElementById('resources'); if(el) el.innerHTML=r.map((x,i)=>`<p>${x.name} ${x.type} ${x.loc} <button onclick='delRes(${i})'>Delete</button></p>`).join('')}
function delRes(i){let r=g('resources',[]);r.splice(i,1);s('resources',r);renderResources()}
function addRequest(){let q=g('requests',[]);q.push({need:qname.value,loc:qloc.value,priority:qpri.value,status:'Pending'});s('requests',q);renderRequests()}
function renderRequests(){let q=g('requests',[]);let el=document.getElementById('requests'); if(el) el.innerHTML=q.map(x=>`<p>${x.need} ${x.loc} ${x.priority} ${x.status}</p>`).join('')}
function autoAllocate(){let q=g('requests',[]),r=g('resources',[]),h=g('history',[]);let req=q.find(x=>x.status==='Pending');if(!req){allocmsg.innerText='No pending requests';return;}let res=r.find(x=>x.status==='Available'&&(x.type.toLowerCase().includes(req.need.toLowerCase())||req.need.toLowerCase().includes(x.type.toLowerCase())));if(!res)res=r.find(x=>x.status==='Available');if(!res){allocmsg.innerText='No resources available';return;}res.status='Allocated';req.status='Assigned';h.push({request:req.need,resource:res.name,time:new Date().toLocaleString()});s('resources',r);s('requests',q);s('history',h);allocmsg.innerText='Assigned '+res.name+' to '+req.need;}
function renderHistory(){let h=g('history',[]);let el=document.getElementById('history'); if(el) el.innerHTML=h.map(x=>`<p>${x.time}: ${x.resource} -> ${x.request}</p>`).join('')}
